# Generated by Django 3.0.7 on 2020-06-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_base_unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
