# Generated by Django 3.0.7 on 2020-06-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_unit_to_base_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='to_base_unit',
            new_name='to_base_multiplier',
        ),
    ]
