# Generated by Django 3.0.7 on 2020-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_auto_20200605_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_base_adder',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
