# Generated by Django 3.0.7 on 2020-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0004_unit_to_base_adder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
