# Generated by Django 3.0.7 on 2020-06-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0005_updatecurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateCurrency',
        ),
    ]
