# Generated by Django 3.0.7 on 2020-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0007_updatecurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecurrency',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
