# Generated by Django 3.0.7 on 2020-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0009_auto_20200605_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
