# Generated by Django 3.0.7 on 2020-06-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0010_unit_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_value', models.FloatField()),
                ('destination_value', models.FloatField()),
                ('destination_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user_interface.Type')),
                ('source_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='user_interface.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
