# Generated by Django 3.0.7 on 2020-06-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0011_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
